Repository elixirsc/git-pair, pull requests merged in 2020-03, with the labels that each got.

#1 Add details to README
  README.md
Labels: documentation, task

#10 Setup GitHub Actions
  .github/workflows/elixir.yml
Labels: tech debt

#11 Add GitHub Actions to README
  README.md
Labels: documentation

#12 Add .sourcelevel.yml set to latest Credo version
  .sourcelevel.yml
Labels: tech debt

#13 Move Contributing section in README to CONTRIBUTING
  CONTRIBUTING.md
  README.md
Labels: enhancement

#17 Fix typo mistake in README file
  README.md
Labels: documentation

#19 Print action output message
  lib/git_pair/cli.ex
Labels: enhancement
